### ISSUE TITLE
Shakmaty support added to chess_perft

### ISSUE THREAD

**Issue by jordanbray** [niklasf/shakmaty#15]
Just an FYI, I added shakmaty to the chess_perft crate/binary, so that it could use either move generator in the background, depending on the use case (with -c or -s).  Additionally, I added all the benchmarks from the 'chess' crate to the 'chess_perft' crate, and a fancy python script to compare and graph performance.
You can run the performance tests yourself with cargo bench in the chess_perft library, which will look at both chess and shakmaty.

**Comment by niklasf** [comment]
Awesome, and thanks for the heads up. I am getting the same results and added a [benchmark](https://github.com/niklasf/shakmaty#benchmarks) to the README.

Also I still want to work with (and on) your library at some point, maybe using it as a dependency of shakmaty to keep supporting all the chess variants, but take advantage of your fast implementation of standard chess.
