### ISSUE TITLE
Correctly support Put

### ISSUE THREAD

**Issue by antoyo** [niklasf/shakmaty#29]
Hi.
It seems this library have support for the CrazyHouse variant, but it does not seem to work for me.
Adding the following line [here](https://github.com/niklasf/shakmaty/blob/master/src/san.rs#L278) (even though it's probably not the correct fix) allows me to play CrazyHouse games:
```rust
                legals.push(Move::Put { role, to });
```
Thanks to fix this issue.

**Comment by niklasf** [comment]
Mhh ... this is exactly what's supposed to happen here:
https://github.com/niklasf/shakmaty/blob/133c704a9ef9fc8d7b7b8a074d1229f28c33a56c/src/position.rs#L1197

Maybe some more context could help to try and reproduce this.

**Comment by antoyo** [comment]
Ah, I think I understand what is going on:
I'm not actually using a CrazyHouse game, but a BugHouse game, so the pocket is probably not filled.
Any workaround for that?

**Comment by niklasf** [comment]
Unfortunately no. Since the implementation details are (intentionally) sealed, a crate implementing Bughouse on top of this one would have to reimplement parts of Crazyhouse or provide a wrapper that keeps setting up Crazyhouse positions with the current pockets.
