### ISSUE TITLE
Direct initialization using bitboards

### ISSUE THREAD

**Issue by Tearth** [niklasf/shakmaty#60]
It would be very handy if there was a way to initialize the position using directly bitboard values like below, instead of using FEN:

```rust
let b = shakmaty::Board {
	by_role: shakmaty::ByRole {
		pawn: shakmaty::Bitboard(0x00ff_0000_0000_ff00),
		knight: shakmaty::Bitboard(0x4200_0000_0000_0042),
		bishop: shakmaty::Bitboard(0x2400_0000_0000_0024),
		rook: shakmaty::Bitboard(0x8100_0000_0000_0081),
		queen: shakmaty::Bitboard(0x0800_0000_0000_0008),
		king: shakmaty::Bitboard(0x1000_0000_0000_0010),
	},
	by_color: shakmaty::ByColor {
		black: shakmaty::Bitboard(0xffff_0000_0000_0000),
		white: shakmaty::Bitboard(0xffff),
	},
	occupied: shakmaty::Bitboard(0xffff_0000_0000_ffff),
};

let chess = shakmaty::Chess::from_setup(
	Setup {
		board: b,
		turn: shakmaty::Color::White,
		ep_square: None,
		halfmoves: 0,
		fullmoves: NonZeroU32::new(1).unwrap(),
		promoted: shakmaty::Bitboard::default(),
		pockets: None,
		castling_rights: shakmaty::Bitboard::default(),
		remaining_checks: None,
	},
	CastlingMode::Standard,
)
.unwrap();
```

Now, shakamaty::Board's fields are private, so it's impossible. I'm integrating shakmaty-syzygy with my bitboard-based chess engine where going through the whole process of making and then parsing FENs can be pretty slow, so I'm looking for a faster way.

**Comment by niklasf** [comment]
Something like fb656ed4d9ffe626627b9055761515ed45711198?

**Comment by Tearth** [comment]
Perfect! Using these methods would be a huge improvement in my engine for sure.

**Comment by niklasf** [comment]
Cool.

One more thing: shakmaty-syzygy prioritizes robustness over performance. Unlike Stockfish's C++ implementation, it will not crash on corrupted tables, and also uses `pread` instead of `mmap` (easier to correctly handle I/O errors, but each access is a syscall). This may not be the right tradeoff for an engine. But maybe it's good enough.

**Comment by Tearth** [comment]
I'm aware, that's why last time I had an attempt of integrating [Fathom](https://github.com/jdart1/Fathom) library through FFI (Foreign Function Interface) with [Inanis](https://github.com/Tearth/Inanis) - while it was somehow working, I had a lot of issues like:
 - segmentation faults on ARM platform even before entering `main` function (interesting fact: it was happening only when std::mutex from C++11 was used, after switching to traditional pthreads of WinAPI calls it was ok)
 - `munmap` calls returning bad statuses

I couldn't find any solution yet for these two, so for now I'm using shakmaty-syzygy to probe tablebases only at the root position (not during search), so it's not hurting performance at all.
