### ISSUE TITLE
Implement Hash & PartialEq on variants

### ISSUE THREAD

**Issue by UE2020** [niklasf/shakmaty#68]
The `Chess` struct has `Hash` & `PartialEq` implemented, while all the variants do not. Is there any reason why, or is it just a missing feature?

**Comment by niklasf** [comment]
Just a missing feature. Would be nice to have.

**Comment by UE2020** [comment]
I've made a pull request (#69) which implements Hash and PartialEq on every variant. However, is there any reason why the en passant square is not hashed in the implementation for `Chess`? I copied your original implementation for all the variants but I'm wondering if this is intentional or it's a mistake.
