### ISSUE TITLE
Using `Move::Put` results in an illegal move

### ISSUE THREAD

**Issue by davebrent** [niklasf/shakmaty#70]
The following snippet fails when I think it should pass

```rust
let pos = Chess::default();
assert!(pos.is_legal(&Move::Put {
    role: Role::Pawn,
    to: Square::D4
}));
```

In [the method](https://github.com/niklasf/shakmaty/blob/b64820bdae0908d82438183e7a1271acaf6d3de5/src/position.rs#L514C1-L525C6), the move list does contain the valid move, but it has constructed a type of `Move::Normal` so the `.contains(m)` fails when using `Move::Put`
```rust
fn is_legal(&self, m: &Move) -> bool {
    ...
    moves.contains(m)
}
```

**Comment by niklasf** [comment]
`Move::Put` refers to the chess variant Crazyhouse, where players can take a captured piece out of their pocket and put it on the board.

I was going to link the documentation, but it is nowhere clearly stated. Will fix.
