### ISSUE TITLE
Mirror boards

### ISSUE THREAD

**Issue by mlomb** [niklasf/shakmaty#74]
Hi, I'm looking for a way to mirror boards. For example, with [python-chess](https://python-chess.readthedocs.io) I can do [`.mirror()`](https://python-chess.readthedocs.io/en/latest/core.html#chess.BaseBoard.mirror):

```python
import chess
board = chess.Board(fen="6k1/pp3pp1/4b2p/4N3/2p5/2q3P1/P4PKP/3r4 w - - 0 1")
print(board.mirror().fen()) # 3R4/p4pkp/2Q3p1/2P5/4n3/4B2P/PP3PP1/6K1 b - - 0 1
```
![fens](https://github.com/niklasf/shakmaty/assets/5845105/654d7071-ef54-497c-9eb6-cf1d5132cb5e)

Which flips vertically and swaps colors.

I tried the same thing with `shakmaty` but only managed to flip the board, and can't find a way to swap colors:

```rust
let fen: Fen = "6k1/pp3pp1/4b2p/4N3/2p5/2q3P1/P4PKP/3r4 w - - 0 1"
    .parse()
    .unwrap();
let pos: Chess = fen.into_position(CastlingMode::Standard).unwrap();
let mut board = pos.board().clone();
board.flip_vertical();
println!("{}", board); // 3r4/P4PKP/2q3P1/2p5/4N3/4b2p/pp3pp1/6k1
```

![image](https://github.com/niklasf/shakmaty/assets/5845105/99c3f93a-59d3-4441-8926-8e5f73897675)

How could I do it? Can it be added to `shakmaty`?

----------

I'm looking for this because I'm working with ML and need the board to always be from the POV of white

Thanks!

**Comment by niklasf** [comment]
Hi. Sure, added `Board::swap_colors()`.
